/*-
 * ===============LICENSE_START=======================================================
 * Acumos
 * ===================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
 * ===================================================================================
 * This Acumos software file is distributed by AT&T and Tech Mahindra
 * under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *  
 *      http://www.apache.org/licenses/LICENSE-2.0
 *  
 * This file is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ===============LICENSE_END=========================================================
 */

package org.acumos.cds.repository;

import javax.transaction.Transactional;

import org.acumos.cds.domain.MLPCatSolMap;
import org.acumos.cds.domain.MLPCatalog;
import org.acumos.cds.domain.MLPSolution;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;

public interface CatSolMapRepository extends PagingAndSortingRepository<MLPCatSolMap, MLPCatSolMap.CatSolMapPK> {

	/**
	 * Gets all entries with the specified solution ID. Generated by Spring magic.
	 * 
	 * @param solutionId
	 *                       Solution ID
	 * @return Iterable of MLPCatSolMap entries
	 */
	Iterable<MLPCatSolMap> findBySolutionId(@Param("solutionId") String solutionId);

	/**
	 * Deletes all entries for the specified solution ID. Generated by Spring magic.
	 * 
	 * @param solutionId
	 *                       Solution ID
	 */
	@Modifying
	@Transactional // throws exception without this
	void deleteBySolutionId(@Param("solutionId") String solutionId);

	/**
	 * Gets the count of solutions within a catalog.
	 * 
	 * @param catalogId
	 *                      Catalog ID
	 * @return Count of solutions
	 */
	@Query("SELECT COUNT(solutionId) FROM MLPCatSolMap WHERE catalogId = :catalogId")
	long countCatalogSolutions(@Param("catalogId") String catalogId);

	/**
	 * Gets a page of solutions in the specified catalog by joining on the
	 * catalog-solution mapping table.
	 * 
	 * @param catalogIds
	 *                       Catalog IDs
	 * @param pageable
	 *                       Page and sort criteria
	 * @return Page of MLPSolution
	 */
	@Query(value = "SELECT s FROM MLPSolution s, MLPCatSolMap m " //
			+ " WHERE s.solutionId = m.solutionId " //
			+ " AND m.catalogId in (:catalogIds)")
	Page<MLPSolution> findSolutionsByCatalogIds(@Param("catalogIds") String[] catalogIds, Pageable pageable);

	/**
	 * Gets all catalogs for the specified solution by joining on the
	 * catalog-solution mapping table.
	 * 
	 * @param solutionId
	 *                       Solution ID
	 * @return Iterable of MLPCatalog
	 */
	@Query(value = "SELECT c from MLPCatalog c, MLPCatSolMap m " //
			+ " WHERE c.catalogId = m.catalogId " //
			+ " AND m.solutionId = :solutionId")
	Iterable<MLPCatalog> findCatalogsBySolutionId(@Param("solutionId") String solutionId);

	/**
	 * Gets the count of catalogs with the specified access-code type and containing
	 * the specified solution.
	 * 
	 * @param accessType
	 *                       Access-type Code; e.g., "PB"
	 * 
	 * @param solutionId
	 *                       Solution ID
	 * @return Count of catalogs matching the criteria
	 */
	@Query(value = " SELECT COUNT(c.catalogId) FROM MLPCatalog c, MLPCatSolMap m " //
			+ " WHERE c.catalogId = m.catalogId " //
			+ " AND c.accessTypeCode = :accessType " //
			+ " AND m.solutionId = :solutionId ")
	long countCatalogsByAccessAndSolution(@Param("accessType") String accessType,
			@Param("solutionId") String solutionId);

}
