/*-
 * ===============LICENSE_START=======================================================
 * Acumos
 * ===================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
 * ===================================================================================
 * This Acumos software file is distributed by AT&T and Tech Mahindra
 * under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *  
 *      http://www.apache.org/licenses/LICENSE-2.0
 *  
 * This file is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ===============LICENSE_END=========================================================
 */

package org.acumos.cds.repository;

import javax.transaction.Transactional;

import org.acumos.cds.domain.MLPSolRevArtMap;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

public interface SolRevArtMapRepository extends CrudRepository<MLPSolRevArtMap, MLPSolRevArtMap.SolRevArtMapPK> {

	/**
	 * Finds map entries for the specified artifact ID.
	 * 
	 * Generated by Spring magic.
	 * 
	 * Not defined as pageable because the number of artifacts for a revision is
	 * expected to be modest.
	 * 
	 * @param artifactId
	 *                       artifact ID
	 * @return Iterable of MLPSolRevArtMap
	 */
	Iterable<MLPSolRevArtMap> findByArtifactId(@Param("artifactId") String artifactId);

	/**
	 * Finds map entries for the specified revision ID.
	 * 
	 * Generated by Spring magic.
	 * 
	 * Not defined as pageable because the number of artifacts for a revision is
	 * expected to be modest.
	 * 
	 * @param revisionId
	 *                       revision ID
	 * @return Iterable of MLPSolRevArtMap
	 */
	Iterable<MLPSolRevArtMap> findByRevisionId(@Param("revisionId") String revisionId);

	/**
	 * Deletes all entries for the specified revision ID
	 * 
	 * Generated by Spring magic.
	 * 
	 * @param revisionId
	 *                       Revision ID
	 */
	@Modifying
	@Transactional // throws exception without this
	void deleteByRevisionId(@Param("revisionId") String revisionId);

	/**
	 * Deletes all entries for the specified artifact ID
	 * 
	 * Generated by Spring magic.
	 * 
	 * @param artifactId
	 *                       Artifact ID
	 */
	@Modifying
	@Transactional // throws exception without this
	void deleteByArtifactId(@Param("artifactId") String artifactId);

}
