/*-
 * ===============LICENSE_START=======================================================
 * Acumos
 * ===================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
 * ===================================================================================
 * This Acumos software file is distributed by AT&T and Tech Mahindra
 * under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *  
 *      http://www.apache.org/licenses/LICENSE-2.0
 *  
 * This file is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ===============LICENSE_END=========================================================
 */
package org.acumos.cds.repository;

import org.acumos.cds.domain.MLPTaskStepResult;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.transaction.annotation.Transactional;

public interface TaskStepResultRepository extends PagingAndSortingRepository<MLPTaskStepResult, Long> {

	/**
	 * Gets all step results with the specified task ID.
	 * 
	 * @param taskId
	 *                   Task ID
	 * @return Iterable of MLPTaskStepResult
	 */
	Iterable<MLPTaskStepResult> findByTaskId(long taskId);

	/**
	 * Deletes all step results for the specified task ID.
	 * 
	 * Generated by Spring magic.
	 * 
	 * @param taskId
	 *                   Task ID
	 */
	@Modifying
	@Transactional // throws exception without this
	void deleteByTaskId(long taskId);

}
